FROM debian:bullseye@sha256:630454da4c59041a2bca987a0d54c68962f1d6ea37a3641bd61db42b753234f2
SHELL ["/bin/bash", "-c"]

ENV CORE_BUILD_DEPS="autoconf autotools-dev automake libtool pkg-config bsdmainutils build-essential"
ENV ESPLORA_BUILD_DEPS="clang cmake curl git"
RUN mkdir -p /srv/explorer \
 && apt-get -yqq update \
 && apt-get -yqq upgrade \
 && apt-get -yqq install ${ESPLORA_BUILD_DEPS} tor ${CORE_BUILD_DEPS}


RUN git clone --quiet --depth 1 --single-branch --branch v0.39.0 https://github.com/nvm-sh/nvm.git /root/.nvm \
 && rm -rf /root/.nvm/.git \
 && source /root/.nvm/nvm.sh \
 && nvm install v17.1.0

# Build core from sources until PR https://github.com/bitcoin/bitcoin/pull/23387 is merged
ENV CORE_PATCH=contrib/0001-add-support-to-save-fee-estimates-without-shutting-d.patch
ENV CORE_SRC=/root/bitcoin
COPY ${CORE_PATCH} /${CORE_PATCH}
RUN git clone --quiet --depth 1 --branch v24.1 --single-branch --recursive https://github.com/bitcoin/bitcoin.git ${CORE_SRC} \
 && (cd ${CORE_SRC} \
 && git checkout 3116ccd790e76de8f64d2ef9aa5a2641c15bbd8b \
 && git apply /${CORE_PATCH} \
 && (cd depends \
 && make HOST=aarch64-linux-gnu NO_QT=1 -j $(nproc --all)) \
 && ./autogen.sh \
 && CONFIG_SITE=$PWD/depends/aarch64-linux-gnu/share/config.site ./configure --prefix=/srv/explorer/bitcoin --disable-man --disable-zmq --disable-qt --disable-gui-tests --disable-bench \
                --enable-experimental-asm --without-utils --enable-util-cli --without-libs --with-daemon --disable-maintainer-mode \
                --disable-glibc-back-compat --disable-ccache --disable-dependency-tracking --disable-tests --with-gui=no \
 && make -j $(nproc --all) \
 && make install -j $(nproc --all) \
 && strip /srv/explorer/bitcoin/bin/* \
 && rm -fr ${CORE_SRC} /${CORE_PATCH})

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.65.0
RUN source /root/.cargo/env \
 && mkdir -p /srv/explorer/electrs \
 && git clone --no-checkout https://github.com/blockstream/electrs.git \
 && (cd electrs \
 && git checkout fd35014283c7d3a7a85c77b9fd647c9f09de12c9 \
 && cp contrib/popular-scripts.txt /srv/explorer \
 && cargo install --root /srv/explorer/electrs_bitcoin --locked --path . --features electrum-discovery \
    ) \
 && rm -fr electrs \
 && strip /srv/explorer/electrs_*/bin/electrs

# Install websocat v1.9.0 with none of the default features, which aren't needed (ssl, subprocess support and stdio support)
RUN source /root/.cargo/env \
 && git clone --no-checkout https://github.com/vi/websocat \
 && (cd websocat \
 && git checkout 9f301bd82bbb28e385a5020870738f98ab9010b1 \
 && cargo install --root /srv/explorer/websocat --locked --path . --no-default-features \
    ) \
 && strip /srv/explorer/websocat/bin/websocat \
 && rm -fr /root/.cargo websocat

# cleanup
RUN apt-get --auto-remove remove -yqq --purge ${ESPLORA_BUILD_DEPS} manpages ${CORE_BUILD_DEPS} \
 && apt-get clean \
 && apt-get autoclean \
 && rm -rf /usr/share/doc* /usr/share/man /usr/share/postgresql/*/man /var/lib/apt/lists/* /var/cache/* /tmp/* /root/.cache /*.deb /root/.cargo